Add  and Remove books
ericmahare/books-store pull request #2
Opened 2022-06-06 22:09 UTC by ericmahare

### In this section I did the following : -

- [ ] Add redux to the project
- [ ] Added a books action and reducer
- [ ] connected components with the global redux state

2022-06-06 23:29 UTC, BenMukebo requested changes
### Hi @ericmahare,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- Descriptive PR. ✔️ 
- No linter errors. ✔️ 
- Gitflow was correctly used.  ✔️   
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-06 23:29 UTC, BenMukebo commented on src/redux/books/books.js
> +const REMOVE = 'REMOVE';
- [ ] Great work so far 👏🏻 h, but the file structure should follow the duck pattern shown below👇🏻 . Please include the category footer and then create a categories.js file within the template.😄 

```
    /src
        |---/components
        |---/redux
            |--- /books
                    | books.js
            |--- /categories
                    | categories.js
            | cofigureStore.js
        | index.js
```

2022-06-06 23:29 UTC, BenMukebo commented on src/redux/configurationStore.js
> +})
- [ ] Please after creating the category footer directory and adding the categories.js file within you would need to import `categoriesReducer` from `src/redux/categories`.
- It will be something like this: `import categoriesReducer from "./categories/categories";`.

2022-06-06 23:29 UTC, BenMukebo commented on src/redux/configurationStore.js
> +})
- [ ] The use `combineReducers` to create a reducer. However, it appears that you have only added the `booksReducer` to the `combineReducers`. Could you please consider adding the `categoriesReducer` to the list of combineReducers?

2022-06-06 23:29 UTC, BenMukebo commented on src/redux/configurationStore.js
> +export default store
- [OPTIONAL] 🤔 What If you Import `applyMiddleware`  to use some handy Redux middleware, like a redux logger.  it will help you a lot in the development process. 👍🏻 To install it, you need to run: 

  ```  npm i --save redux-logger  ```

2022-06-07 09:41 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @ericmahare,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-07 10:44 UTC, merged